/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulationRouteImport } from './routes/_app.simulation'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCorridorsRouteImport } from './routes/_app.corridors'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulationRoute = AppSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCorridorsRoute = AppCorridorsRouteImport.update({
  id: '/corridors',
  path: '/corridors',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/corridors': typeof AppCorridorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/reports': typeof AppReportsRoute
  '/simulation': typeof AppSimulationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/corridors': typeof AppCorridorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/reports': typeof AppReportsRoute
  '/simulation': typeof AppSimulationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/corridors': typeof AppCorridorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/simulation': typeof AppSimulationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/corridors'
    | '/dashboard'
    | '/recommendations'
    | '/reports'
    | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/corridors'
    | '/dashboard'
    | '/recommendations'
    | '/reports'
    | '/simulation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/corridors'
    | '/_app/dashboard'
    | '/_app/recommendations'
    | '/_app/reports'
    | '/_app/simulation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulation': {
      id: '/_app/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof AppSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corridors': {
      id: '/_app/corridors'
      path: '/corridors'
      fullPath: '/corridors'
      preLoaderRoute: typeof AppCorridorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCorridorsRoute: typeof AppCorridorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSimulationRoute: typeof AppSimulationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCorridorsRoute: AppCorridorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSimulationRoute: AppSimulationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
